name: CI - Build, Lint & Test Next.js App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # Setup pnpm correctly
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      # Verify pnpm is available
      - name: Verify pnpm
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint (warnings only)
        run: pnpm lint || echo "Lint errors detected, continuing workflow..."

      - name: Run tests
        run: pnpm test --if-present

      - name: Build Next.js app
        run: pnpm run build
